name: microbosh-azure

logging:
  level: debug
  file: /tmp/run.log

network:
  type: manual
  ip: 10.0.0.5
  cloud_properties:
    virtual_network_name: boshvnet-crp
    subnet_name: BOSH
    tcp_endpoints:
    - "22:22"
    - "53:53"
    - "4222:4222"
    - "6868:6868"
    - "25250:25250"
    - "25555:25555"
    - "25777:25777"
    udp_endpoints:
    - "68:68"

resources:
  persistent_disk: 50000
  cloud_properties:
    instance_type: Standard_A1

cloud:
  plugin: azure
  properties:
    azure:
      environment: AzureCloud
      api_version: 2015-05-01-preview
      subscription_id: Your subscription id
      storage_account_name: Your storage account name
      storage_access_key: The access key of your storage account
      resource_group_name: Your resource group name
      client_id: Your client id of the service principle
      client_secret: Your client secret of the service principle
      tenant_id: Your tenant id of the service principle
      ssh_certificate: The content of your ssh certificate
      ssh_private_key: The content of your ssh private key

apply_spec:
  agent:
    blobstore: {address: 10.0.0.5}
    nats:{address: 10.0.0.5}
  properties:
    registry:{address: 10.0.0.5}

